- platform: rest
  name: espresso stats
  json_attributes:
    - Runtime
    - Input
  resource: http://192.168.1.240/json
  value_template: "{{ value_json.Mode }}"
- platform: template
  sensors:
    espresso_runtime:
      friendly_name: "runtime"
      value_template: '{{ ( states.sensor.espresso_stats.attributes["Runtime"] / 60 ) | round(0) }}'
    espresso_input:
      friendly_name: "input"
      value_template: '{{ states.sensor.espresso_stats.attributes["Input"] }}'
